version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: '0 * * * *'
    labels:
      - mergewhenready
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - mergewhenready
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    labels:
      - mergewhenready
